### ISSUE TITLE
Add a gef config options to disable pager in command output

### ISSUE THREAD

**Issue by nobodyisnobody** [bata24/gef#3]
Hi,
first of all.. great work !

is it possible to add a gef config options to disable pager in output of commands like hexdump, vmmap, etc.., without having to add -n option each time ?

-n option does not seems to work with vmmap

**Comment by bata24** [comment]
A `gef.always_no_pager` config was introduced. see commit dde3ee8.

The reason why pager works in vmmap and the `-n` option does not work is probably because you typed `vmmap` during connected qemu-system gdb stub.
In this case, all options are ignored and just redirect to `pagewalk`.
So use the `pagewalk` command instead of `vmmap` command if you'd like to use some option.

**Comment by nobodyisnobody** [comment]
Nice, works well. thanks
