### ISSUE TITLE
Add support Uclibc 32 bits

### ISSUE THREAD

**Issue by joko99999** [bata24/gef#4]
Can you please add support at Uclibc(not ng version)  32bits?

**Comment by bata24** [comment]
Maybe there is no toolchain (gcc, binutils, headers, library set) available. I looked for toolchain of i686 + uclibc 0.9.33.2, but I couldn't find it. So it's hard to test without it, so I won't be able to support it.

**Comment by bata24** [comment]
The following are the results of my research after this issue was closed.
In addition, since the toolchain has not been found yet, it is all based on guesses from the source code.

1. uclibc(malloc-standard) and uclibc-ng(malloc-standard) have the same malloc structure. Therefore, `ucilibc-ng-heap-dump` command also can be used for ucilibc (non-ng version).

2. We cannot get the address of `malloc_state` under the condition that the symbol does not exist. Therefore, `uclibc-ng-heap-dump` command will definitely fail. This is the same for uclibc (non-ng version).

3. Implementations other than malloc-standard (malloc, malloc-simple) have not found a reliable toolchain too. Therefore, it seems difficult to implement dump commands for these.
