### ISSUE TITLE
a bug for hardware breakpoint

### ISSUE THREAD

**Issue by henrymartin262** [bata24/gef#73]
hello your tools are great, buf I meet this problem "AttributeError: 'NoneType' object has no attribute 'startswith'" when I set a hardware breakpoint, and I dont know how to solve it

**Comment by henrymartin262** [comment]
![Snipaste_2024-04-10_15-49-00](https://github.com/bata24/gef/assets/55277069/efce5fd9-fe09-4ed5-9ebc-7bb47f441559)

**Comment by bata24** [comment]
Hello, thank you for your report.
Although I have not been able to reproduce it, it seems that the cause is that the `location` member of the breakpoint object is `None`.
I think this probably fixed it. See 48037be74741bb69c1b50962ddbbfa2b06841b89 .

Please update to the latest version and try it out.
If it is not fixed, please report again.

**Comment by henrymartin262** [comment]
yeah, the bug has fixed that the window return to normal. Thanks!
